/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyMarkRouteImport } from './routes/why-mark'
import { Route as MeetMarkRouteImport } from './routes/meet-mark'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyMarkRoute = WhyMarkRouteImport.update({
  id: '/why-mark',
  path: '/why-mark',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetMarkRoute = MeetMarkRouteImport.update({
  id: '/meet-mark',
  path: '/meet-mark',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-mark': typeof MeetMarkRoute
  '/why-mark': typeof WhyMarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-mark': typeof MeetMarkRoute
  '/why-mark': typeof WhyMarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/meet-mark': typeof MeetMarkRoute
  '/why-mark': typeof WhyMarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/meet-mark' | '/why-mark'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/meet-mark' | '/why-mark'
  id: '__root__' | '/' | '/about' | '/meet-mark' | '/why-mark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MeetMarkRoute: typeof MeetMarkRoute
  WhyMarkRoute: typeof WhyMarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-mark': {
      id: '/why-mark'
      path: '/why-mark'
      fullPath: '/why-mark'
      preLoaderRoute: typeof WhyMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-mark': {
      id: '/meet-mark'
      path: '/meet-mark'
      fullPath: '/meet-mark'
      preLoaderRoute: typeof MeetMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MeetMarkRoute: MeetMarkRoute,
  WhyMarkRoute: WhyMarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
